name: crime_mitigation_system
description: Mobile Baes Crime Mitigation System.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-12.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  line_awesome_flutter: ^2.0.0
  google_fonts: 
  camera: 
  path:
  path_provider:
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: "^1.2.0"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  
flutter_native_splash:

  color: "#FFFFFF"
  image: assets/images/ImageIcon.png

# fonts:
#     - family: Muli
#       fonts:
#         - asset: assets/fonts/muli/Muli.ttf
#         - asset: assets/fonts/muli/Muli-Bold.ttf
#           weight: 700
#         - asset: assets/fonts/muli/Muli-light.ttf
#           weight: 300
